apiVersion: v1
kind: Namespace
metadata:
  name: webhook
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mutating-webhook
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mutating-webhook-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mutating-webhook
subjects:
  - kind: ServiceAccount
    name: default
    namespace: webhook
---
apiVersion: v1
kind: Service
metadata:
  name: node-selector
  namespace: webhook
  labels:
    app: node-selector
spec:
  ports:
    - port: 443
      targetPort: 443
  selector:
    app: node-selector
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: node-selector
  namespace: webhook
  labels:
    app: node-selector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-selector
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: node-selector
    spec:
      volumes:
        - name: volume-h9oo0c
          secret:
            secretName: node-selector
            items:
              - key: cert.pem
                path: cert.pem
              - key: key.pem
                path: key.pem
            defaultMode: 420
      containers:
        - name: node-selector
          image: '364554757/webhook:v2.2.2'
          ports:
            - name: https
              containerPort: 443
              protocol: TCP
          resources: {}
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: volume-h9oo0c
              readOnly: true
              mountPath: /etc/webhook
      restartPolicy: Always
      dnsPolicy: ClusterFirst
      serviceAccountName: default
      serviceAccount: default
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 2
  progressDeadlineSeconds: 600
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: high-priority
value: 1000000
globalDefault: false
description: "This priority class should be used for Test pods only."
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: medium-priority
value: 100000
globalDefault: false
description: "This priority class should be used for Test pods only."
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: low-priority
value: 10000
globalDefault: false
description: "This priority class should be used for Test pods only."